Task(1)
Linear_model

In [5]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import mean_squared_error , r2_score
from sklearn.model_selection import train_test_split

In [3]:
data=pd.read_csv(r"C:\Users\moham\Downloads\train.csv")
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [6]:
df=pd.DataFrame(data)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [8]:
X = data[['GrLivArea', 'BedroomAbvGr', 'FullBath']]
y = data['SalePrice']

x_train ,x_test ,y_train ,y_test =train_test_split(X,y,test_size=.2,random_state=42)
model=linear_model.LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)

[113410.67255298 305081.87775899 135904.78562983 205424.67564124
 227502.68349004 121157.48079629 205577.98056584 183787.20378269
 121157.48079629 147219.22233196 185971.75622995  93229.5689926
 121965.26049018 192005.28203666 208129.35962356 133824.25948958
 211250.14883393 146931.57417313 134240.36471763 186179.80884397
 219884.33231595 197726.72892233 185867.72992294 126334.3653847
 181186.54610738 183707.60823788 171720.15216927 118844.47127982
 199183.09722051 199623.63321076 132551.51304323 245162.72491993
 383364.40832164 127998.78629689 202511.9390449  120484.46142981
 200376.66521523 206232.45533514 241160.86372906 120716.94480604
 124645.5137103  251820.40856871 101135.56832553 244746.61969188
 105088.56799199 208912.70855526 123837.7340164  101655.69986059
 271169.30167299 160846.66855057 105088.56799199 221989.28921839
 137960.88100787 360448.30385172 143835.21572496 212706.5171321
 216971.5957196  149458.52246864 118507.96159658 114995.49792036
 109714.58702494 131927.35520116 262926.79265682 215643.68449065
 217075.62202662 230158.50594796 136528.9434719  240977.24187723
 103632.19969382 210650.42175406 165350.11667932 128286.43445573
  96662.437124   167167.42542293 304898.25590717 163263.70437405
 281155.82714617 283860.51112849 121940.82972798 110106.26149078
 131639.70704232 141002.07467343 131743.73334934 121133.05003408
 147947.40648105 165943.95759417 234031.91006961 180115.96611004
 143835.21572496 183787.20378269 191142.75465334 174192.35277536
 113851.20854323 289661.55355897 189588.24621318 169223.52080097
 193357.62402782 183371.09855464 214811.47403455 250443.63581535
 204696.49149216 216243.41157052 263575.3812611  117804.20820969
 177931.41366278 156061.458428   109041.56765846 240193.89294554
 105296.62060602 165374.9645347  138841.95298837 140512.26006559
 110497.93595663 133047.21381609 219260.17447387 112602.89285908
 122693.44463927  93021.51637857 203527.77135282 201783.75489581
 135409.08485697 143835.21572496 198766.99199246 167896.0266652
 179210.04627415  99575.17372034 240353.08403516 126230.33907769
 116635.48807036 178769.5102839  196894.51846624 269945.41675105
 217387.70094765 180874.88427953  75539.21063549 211042.0962199
 232673.68191343  99887.25264138 204384.41257112 484661.60058938
 296319.23720776 125502.1549286  212498.46451808 181890.29949427
 112162.35686883  95934.25297492 216292.69018811 181082.51980037
 108857.94580664 118844.47127982 151716.78429569 142538.03851641
 297310.22166029 215570.39220404 114346.90931609 192084.87758147
 183126.84284837 172001.91416308  91901.65776364 121316.67188591
 160693.36362597 162113.5288319  203552.20211502 134399.55580725
 155461.73134813 139606.75732289 235176.19944675 300088.6150224
 334031.50803562 255644.95116596 234552.04160468 147372.11016338
 163997.77468816 194189.83448392 304433.28915472 170863.51095097
 156997.69519111 210938.06991289 170441.5195579  195958.28170313
 163918.17914335 137569.20654202 101551.67355358 146803.11710391
 239233.22542023 210209.88576381 208025.33331655 215019.52664857
 201288.05412295 115907.30392127 170961.65109296 140585.96944538
 165032.15159326 118611.98790359 221493.58844553 271224.04936242
 185341.71222285 139313.22299903 213226.64866716 142017.90698135
 218452.39477998 182746.94071257 142121.93328836 279258.92285775
 171408.07324823 134270.68164485 242458.04093761 118924.06682463
 194887.70170578  95102.04251882 239000.742044   135984.38117464
 129742.8027539  185347.59838787 170753.59847894 195230.09755404
 144796.30034346 121316.67188591 142954.14374446 186051.35177476
  95310.09513284 196710.89661441 203656.22842203 119964.32989475
 184827.46685281 128702.53968378 146307.41633105 106367.20060336
 145426.34435055 151508.73168167 125710.20754262 188468.38759824
 118844.47127982 130158.90798195 231535.27870132 147531.301253
 184643.84500099 132575.94380543 246827.14583212 154996.3475025
 103864.68307005 288804.91234067 213746.78020222 368696.69903291
 200823.0873705  142434.0122094  151172.22199843 177257.97720312
 112578.46209688 111042.4982539  196870.08770403 185451.62469489
 158870.16871734 100847.92016669 122877.06649109 170184.18832629
 129638.77644689 167767.1525028  199079.07091349 249739.88242847
 237568.80450803 127974.35553469  95310.09513284 229999.31485834
 211874.306676   206752.5868702  198063.23860557 143835.21572496
 133512.18056854 181082.51980037 274938.67948764 198063.23860557
 237360.75189401 117987.83006152 186308.26591319 106544.93629017
 210105.85945679 253405.2339361  208851.65760763 164383.56298899
 217075.62202662 121157.48079629 196270.36062416 111354.57717493
 211042.0962199  187220.0719141  223733.3056754  146619.49525209
 191485.1505016  183787.20378269 132735.13489506  92189.30592247]

In [9]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("mean_squared_error=",mse)
print("r2_score=",r2)

mean_squared_error= 2806426667.247853
r2_score= 0.6341189942328371

In [10]:
print(model.coef_)
print(model.intercept_)

[   104.02630701 -26655.16535734  30014.32410896]
52261.748626944594